name: Python Package using Poetry

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os arquivos
        uses: actions/checkout@v3.3.0

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
