name: CI

on:
  push:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:stable-dind 

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and run Docker containers
      run: |
        docker-compose up --build -d  # Subindo os containers em segundo plano
        docker-compose run app sh -c "pytest"  # Executando os testes

    - name: Stop Docker containers
      run: docker-compose down  # Parando os containers após os testes
