name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:stable-dind
        options: --privileged

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and run Docker containers
      run: |
        docker-compose up --build -d
        docker-compose run app sh -c "pytest"

    - name: Stop Docker containers
      run: docker-compose down
